language: node_js

services:
  - docker

node_js:
- 6.9.4

sudo: false

env:
  global:
  - REPO=quay.io/koudaiii/private-isu-portal
  - BRANCH=$(echo $TRAVIS_BRANCH | sed -e "s,/,_,g;")
  - TAG=$BRANCH-${TRAVIS_COMMIT::8}
  # DOCKER_PASSWORD
  - secure: "ziXAXnbO7mMSUK4snxENoxJbyqAoIQPxAtcGUCNfkB0bcsZO0S0UZoXyWSPobKVVva5BnzMQcw6wLB/N1d6JVZR55iVapK8DlgSfGAXDCxYkVl3EOC0YXD/lqSbMbvPZW623sOKhXZfrpvCuRyMz//FnodJW42MC+sO7aXFIkmNYdyLDd1+vF+y6KDh1LtB4PTTGGdFkVhKttqR15d3Oxec9q9KV8rkSphxOFo5nq9RqQK3Hc/QdtTRu5Bx/j1dUVCl9yr209J2O1D5CXe0TwMYkZ/ERWjbw4oRGGo9TZGZH+9HSq1t92bxuUaIJrJMSxaHvITxh3tSs6SUyEW/4ouu9qC2cCFWHFrrGAmvjEVTGAkdlwDeMkaY1JoeZNSXlYke5MlWjP4+U+X5QOMgqZW2snDVC631lWtqk7SuYONUXnYfile5yBGrfiQC8M1KJQC1U7boyyHHyKRBbp2YObNVFx+T8PYi4ZTamxOS5wg7rSyUTCTrUOdZmbRtFao5wcDjBMOvbZ9Bm1TIgBqAw+nwaH5xt1cFzHsf4iLuXA3QBzeTkXNEAekbGQwwUISvmZt9K1pxJhal/wtQzlmN2kmgRHCGeE6fMd11HIoxsMxEsSjx5z82DELCcHIGFUOR3d5ljDKp19TdKknWmJ9dtY0hAhb8VXzKjIiOcUniY0zE="
  # DOCKER_USERNAME
  - secure: "178U89vEtTRsLiFe2L5bAsxGoJBdbbncfDCsTITSnip1M+9zuRRvFiAQGmWvuu/9QSnozy7ESgQyoGYlqMxiag9A1OECSouUIBy9NfUscZE5q5BtBWX2xJdzPfDyiQsRgJ8H4m+KYrFFNGygV/t8rosZ90iahof3cq7+ARCszWv23kTo/g/ZUwsvtT35rXVD0YdyVPudHdXujjkPEMI0G62Unz2Fk6J1jaU3SWA7cagxal9RibJ8OmKiPykLMLbs5YkURjzwdpKQBQ7N3NWYJPH3A357sn2agOQBSQvNi+MJ0V75To49dNMzcNh0KIoRNpndcP5tTerbQVl8MxP2Zg+9UxF5l+1cNcgADY2GCropZQ4Dr7pt6YJbOrFZsMqz69BTXMPLOkHx7SVR8OaG6WfAuwEaU3W+6I0d38qLoRy+8L1tljxCiACig6F6ezXndvkC3AbGpaBe3qdXn/OfpsZdLqnmiD6c1yjrUmarFoRmAl3zcYBk6qizIRy6x+K/zJ9b1Azt5TAU1RxoqoQsjqKJfmpRFUJOSuFvYReIM1/+wtXtfJl+eH3nA82My5s57fDcm6FrPipOTaXOfU0tv6Zeqd0V/tEtLlf40U43yEt3fKnJTp1danXb4TqYUdRhrZ58M+r5dUgxMyBP9vcppGChfwSZo0X19dSxsC/XjPE="
  # FIREBASE_URL
  - secure: "GKbHY2qGHu1EbYYz4JPF2igDsSL7EuCVEl5RZSfvQ+R3z6y6BKTc38v5huO90riklpKzM+CIWUrOlUV69HWvs+SNomkk5aqO5DEMd2QSdzZ3gXvhsKoj73FgGCCgdxerD5nRV7BO24Z0wFzezK+ai1Vi4Uu2lsQlRXvfR/LR7ztREze9sRzOwIbJ64GSun3ATDnUkm5MEKgAx/iBGTiAj8Uwu6YIx21INS+oOA4YAIOTIo0fDRfv0s8ZMQ0CLzZ6Hpgvux5H9tXn6yd8A138gBDqlwMWmnGPOk0nPJrISLdPgKPYPp9tcrk8Lg+rh5A3vvmmSJMp0cZPMMegh2A9c9OFDPFaoQ/yb85Oe5DEXK6GMCkxbQBSR8Ik6jXrduSDjyz0jK8RT5nRp3N+2uz4pKXEfAXG7ugLrcgv3Ti2MA4EqC/qjpcNnBhPcfDzGjDK04sk0HyS3SDlnj9RO/mnBSdxM356F3RabvIeK5Uqnq3laVmP2TeUbsiGjgk5/pBOonHqHVscrkGav5Hm2ORSOCRYZKXjpb9dr5wL3kBth30Voq6B2TztXXe6Wqh7XUPdgMRXjuL4SrnO40darVX/tJrLatuzSjM2ZdJhV80pmneW8LCRHEoGYLGbGDGul5cXWdGXMtnG/HkGb2X90oo9lbsknWGXzbjk3u6FLiC4hYE="

cache:
  directories:
  - node_modules

script:
  - ./scripts/ci-build
