apiVersion: v1
kind: Service
metadata:
  name: private-isu-portal
  namespace: private-isu-portal
  labels:
    name: private-isu-portal
    role: web
spec:
  ports:
  - name: https
    port: 443 # Service opened port.
    protocol: TCP
    targetPort: 80 # Endpoint of Pod
  - name: http
    port: 80 # Service opened port.
    protocol: TCP
    targetPort: 80 # Endpoint of Pod
  selector:
    name: private-isu-portal
    role: web
  type: LoadBalancer
